app = "cbyli"

[[services]]
  internal_port = 9002
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = "443"

[mounts]
  source = "app_db"
  destination = "/app/db"
